### ISSUE TITLE
Error: Invalid backend configuration argument

### ISSUE THREAD

**Issue by autocloudarc** [Azure/alz-terraform-accelerator#108]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:
1.7.3
**azure provider**:
~> 3.88
**module**:
"Azure/caf-enterprise-scale/azurerm"
version 4.2.0
### Description
After the bootstrap process, when I execute the pipeline plan stage, the init fails with the error above in the title where all of the backend arguments are shown as invalid. 

**Describe the bug**
Invalid backend configuration arguments

**Steps to Reproduce**
I completed all steps up to and including the bootstrap process.

3.1.1 Azure DevOps
1. Navigate to [dev.azure.com](https://dev.azure.com/) and sign in to your organization.
2. Navigate to your project.
3. Click Pipelines in the left navigation.
4. Click the Azure Landing Zone Continuous Delivery pipeline.
5. Click Run pipeline in the top right.
6. Take the defaults and click Run.
7. Your pipeline will run a plan.

**Screenshots**

![image](https://github.com/Azure/alz-terraform-accelerator/assets/15109536/9e4f2d25-148d-4c91-bbc8-9d569e185ba7)

**Additional context**

I'm delivering a landing zones deployment engagement tomorrow between 13-15 feb 2024 and would like to get this resolved ASAP if at all possible. Thanks.

**Comment by luke-taylor** [comment]
Hey what starter module is this? Can you show me the `backend` block in the configuration?

**Comment by autocloudarc** [comment]
See also: 

![image](https://github.com/Azure/alz-terraform-accelerator/assets/15109536/6f884e34-569c-4dcc-9ce4-2b51eafbdef5)

and 

![image](https://github.com/Azure/alz-terraform-accelerator/assets/15109536/ef9b571b-f020-4ed9-97f6-d56868e2a19c)

**Comment by jaredfholgate** [comment]
@luke-taylor There is nothing obviously wrong here. My best guess is the required_providers block. It is using the old deprecated syntax. Perhaps this has been deprecated in TF 1.7.3? In the log shared there is no line for the provider being downloaded prior to the error showing. I will try to replicate later today.

**Comment by luke-taylor** [comment]
Couldn't reproduce this with latest version (v1.1.0) and following inputs:
```yaml
allow_storage_access_from_my_ip: "false"
apply_approvers: ""
azure_devops_authentication_scheme: WorkloadIdentityFederation
azure_devops_create_project: "true"
azure_devops_organization_name: luketaylorext
azure_devops_personal_access_token: ****
azure_devops_project_name: alz-demo
azure_devops_use_organisation_legacy_url: "false"
bootstrap_location: uksouth
bootstrap_subscription_id: ****
environment_name: mgmt
postfix_number: 1
root_parent_management_group_display_name: Tenant Root Group
service_name: alz
starter_module: complete
use_private_networking: "true"
use_self_hosted_agents: "true"
use_separate_repository_for_pipeline_templates: "true"

configuration_file_path: ""
default_location: uksouth
default_postfix: landing-zone
root_parent_management_group_id: ""
subscription_id_connectivity: ***
subscription_id_identity: ***
subscription_id_management: ***

```
