### ISSUE TITLE
Error: no configuration files

### ISSUE THREAD

**Issue by autocloudarc** [Azure/alz-terraform-accelerator#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bootstrap or Starter Module Deployment? (Required)

starter_module

### ALZ-PowerShell-Module Version (Required)

1.1.6

### alz-terraform-accelerator Version (Required)

1.1.2

### Starter Module (Required)

complete

### Input arguments of the ALZ-PowerShell-Module (Required)

```YAML
---
starter_module: "complete"
azure_devops_personal_access_token: "***"
azure_devops_organization_name: "autocloudarc"
bootstrap_location: "centralus"
use_separate_repository_for_pipeline_templates: "true"
bootstrap_subscription_id: "***"
service_name: "alz"
environment_name: "mgmt"
postfix_number: "1"
azure_devops_use_organisation_legacy_url: "false"
azure_devops_create_project: "true"
azure_devops_project_name: "prj-tfm-acc-06"
azure_devops_authentication_scheme: "WorkloadIdentityFederation"
use_self_hosted_agents: "false"
use_private_networking: "false"

# Allow access to the storage account from the current IP address. We recommend this is kept off for security
allow_storage_access_from_my_ip: "true"
apply_approvers: "***@microsoft.com"
root_parent_management_group_display_name: "Tenant Root Group"
default_location: "centralus"
default_postfix: "landing-zone"
root_parent_management_group_id: "orgid"
subscription_id_connectivity: "***"
subscription_id_identity: "***"
subscription_id_management: "***"
configuration_file_path: "<base-path>\\v1.1.2\\templates\\complete\\config.yaml"
```

### Contents of the configuration file used for the `complete` starter module. (Optional)

```YAML
# This file contains templated variables to avoid repeating the same hard-coded values.
# Templated variables are denoted by the dollar curly braces token. The following details each templated variable that you can use:
# `default_location`: This is an Azure location sourced from the `default_location` variable. This can be used to set the location of resources.
# `default_postfix`: This is a string sourced from the variable `default_postfix`. This can be used to append to resource names for consistency.
# `root_parent_management_group_id`: This is the id of the management group that the ALZ hierarchy will be nested under.
# `subscription_id_identity`: The subscription ID of the subscription to deploy the identity resources to, sourced from the variable `subscription_id_identity`.
# `subscription_id_connectivity`: The subscription ID of the subscription to deploy the connectivity resources to, sourced from the variable `subscription_id_connectivity`.
# `subscription_id_management`: The subscription ID of the subscription to deploy the management resources to, sourced from the variable `subscription_id_management`.
---
archetypes:  # `caf-enterprise-scale` module, add inputs as listed on the module registry where necessary.
  root_name: es
  root_id: Enterprise-Scale
  subscription_id_connectivity: ${subscription_id_connectivity}
  subscription_id_identity: ${subscription_id_identity}
  subscription_id_management: ${subscription_id_management}
  root_parent_id: ${root_parent_management_group_id}
  deploy_corp_landing_zones: true
  deploy_online_landing_zones: true
  default_location: ${default_location}
  disable_telemetry: true
  deploy_management_resources: true
  configure_management_resources:
    location: ${default_location}
    settings:
      security_center:
        config:
          email_security_contact: "security_contact@replace_me"
    advanced:
      asc_export_resource_group_name: rg-asc-export
      custom_settings_by_resource_type:
        azurerm_resource_group:
          management:
            name: rg-management
        azurerm_log_analytics_workspace:
          management:
            name: log-management
        azurerm_automation_account:
          management:
            name: aa-management
connectivity:
  hubnetworking:  # `hubnetworking` module, add inputs as listed on the module registry where necessary.
    hub_virtual_networks:
      primary:
        name: vnet-hub
        resource_group_name: rg-connectivity
        location: ${default_location}
        address_space:
          - 10.0.0.0/16
        firewall:
          name: fw-hub
          sku_name: AZFW_VNet
          sku_tier: Standard
          subnet_address_prefix: 10.0.1.0/24
        virtual_network_gateway:  # `vnet-gateway` module, add inputs as listed on the module registry where necessary.
          name: vgw-hub
          sku: VpnGw1
          type: Vpn
          subnet_address_prefix: 10.0.2.0/24
```

### Debug Output/Panic Output (Optional)

```shell
##[debug]addSpnToEnvironment=true
##[debug]<guid-redacted> auth scheme = WorkloadIdentityFederation
##[debug]exec tool: /usr/bin/pwsh
##[debug]arguments:
##[debug]   -NoLogo
##[debug]   -NoProfile
##[debug]   -NonInteractive
##[debug]   -ExecutionPolicy
##[debug]   Unrestricted
##[debug]   -Command
##[debug]   . '/home/vsts/work/_temp/azureclitaskscript1708011041085.ps1'
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . '/home/vsts/work/_temp/azureclitaskscript1708011041085.ps1'
Running: terraform plan -out=tfplan -input=false
╷
│ Error: No configuration files
│ 
│ Plan requires configuration to be present. Planning without a configuration
│ would mark everything for destruction, which is normally not what is
│ desired. If you would like to destroy everything, run plan with the
│ -destroy option. Otherwise, create a Terraform configuration file (.tf
│ file) and try again.
╵
##[debug]$LASTEXITCODE: 1
##[debug]Exit code 1 received from tool '/usr/bin/pwsh'
##[debug]STDIO streams have closed for tool '/usr/bin/pwsh'
##[debug]task result: Failed
##[error]Script failed with exit code: 1
##[debug]Processed: ##vso[task.issue type=error;]Script failed with exit code: 1
##[debug]Processed: ##vso[task.complete result=Failed;]Script failed with exit code: 1
##[debug]which 'az'
##[debug]found: '/usr/bin/az'
```

### Expected Behaviour (Required)

The terraform plan task should have executed without an error.

### Actual Behaviour (Required)

The "Terraform plan for apply" task failed.

![image](https://github.com/Azure/alz-terraform-accelerator/assets/15109536/38de9465-fe81-4120-a937-5615532b4ff0)

![image](https://github.com/Azure/alz-terraform-accelerator/assets/15109536/6976ed2f-448a-4d6d-a241-a5e338cca96b)

### Steps to Reproduce (Optional)

Manually run the **02 Azure Landing Zone Continuous Delivery** pipeline from the Azure DevOps pipeline GUI.

### Important Factoids (Optional)

No

### References (Optional)

None.
