### ISSUE TITLE
Invalid value for "path" parameter

### ISSUE THREAD

**Issue by autocloudarc** [Azure/alz-terraform-accelerator#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bootstrap or Starter Module Deployment? (Required)

bootstrap

### ALZ-PowerShell-Module Version (Required)

1.1.6

### alz-terraform-accelerator Version (Required)

1.1.2

### Starter Module (Required)

complete

### Input arguments of the ALZ-PowerShell-Module (Required)

```YAML
cache-bootstrap-local.json
{
  "bootstrap_location": "uksouth",
  "bootstrap_subscription_id": "***93",
  "create_bootstrap_resources_in_azure": "true",
  "environment_name": "boot",
  "postfix_number": "1",
  "root_parent_management_group_display_name": "Tenant Root Group",
  "service_name": "loc",
  "starter_module": "complete",
  "target_directory": ""
}
cache-starter-complete.json
{
  "configuration_file_path": "...<omitted>\v1.1.2\\templates\\complete\\config.yaml",
  "default_location": "uksouth",
  "default_postfix": "lza",
  "root_parent_management_group_id": "***3d",
  "subscription_id_connectivity": "***93",
  "subscription_id_identity": "***da",
  "subscription_id_management": "***3a"
}
```

### Contents of the configuration file used for the `complete` starter module. (Optional)

```YAML
# This file contains templated variables to avoid repeating the same hard-coded values.
# Templated variables are denoted by the dollar curly braces token. The following details each templated variable that you can use:
# `default_location`: This is an Azure location sourced from the `default_location` variable. This can be used to set the location of resources.
# `default_postfix`: This is a string sourced from the variable `default_postfix`. This can be used to append to resource names for consistency.
# `root_parent_management_group_id`: This is the id of the management group that the ALZ hierarchy will be nested under.
# `subscription_id_identity`: The subscription ID of the subscription to deploy the identity resources to, sourced from the variable `subscription_id_identity`.
# `subscription_id_connectivity`: The subscription ID of the subscription to deploy the connectivity resources to, sourced from the variable `subscription_id_connectivity`.
# `subscription_id_management`: The subscription ID of the subscription to deploy the management resources to, sourced from the variable `subscription_id_management`.
---
archetypes:  # `caf-enterprise-scale` module, add inputs as listed on the module registry where necessary.
  root_name: loc
  root_id: local-org
  subscription_id_connectivity: ${subscription_id_connectivity}
  subscription_id_identity: ${subscription_id_identity}
  subscription_id_management: ${subscription_id_management}
  root_parent_id: ${root_parent_management_group_id}
  deploy_corp_landing_zones: true
  deploy_online_landing_zones: true
  default_location: ${default_location}
  disable_telemetry: true
  deploy_management_resources: true
  configure_management_resources:
    location: ${default_location}
    settings:
      security_center:
        config:
          email_security_contact: "email@domain.com"
    advanced:
      asc_export_resource_group_name: rg-asc-export
      custom_settings_by_resource_type:
        azurerm_resource_group:
          management:
            name: rg-management-loc
        azurerm_log_analytics_workspace:
          management:
            name: log-management-loc
        azurerm_automation_account:
          management:
            name: aa-management-loc
connectivity:
  hubnetworking:  # `hubnetworking` module, add inputs as listed on the module registry where necessary.
    hub_virtual_networks:
      primary:
        name: vnet-hub
        resource_group_name: rg-connectivity-loc
        location: ${default_location}
        address_space:
          - 10.0.0.0/16
        firewall:
          name: fw-hub-loc
          sku_name: AZFW_VNet
          sku_tier: Standard
          subnet_address_prefix: 10.0.1.0/24
        virtual_network_gateway:  # `vnet-gateway` module, add inputs as listed on the module registry where necessary.
          name: vgw-hub-loc
          sku: VpnGw1
          type: Vpn
          subnet_address_prefix: 10.0.2.0/24
```

### Debug Output/Panic Output (Optional)

```shell
Plan: 212 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + module_output_directory_path = "C:/Users/uniso/OneDrive/02.00.00.GENERAL/repos/0000-data/local/local"
╷
│ Error: Invalid function argument
│
│   on locals_files.tf line 4, in locals:
│    4:       content = replace((file(value.path)), "# backend \"azurerm\" {}", var.create_bootstrap_resources_in_azure ? "backend \"azurerm\" {}" : "backend \"local\" {}")
│     ├────────────────
│     │ value.path is "C:\\data-uni\\OneDrive\\02.00.00.GENERAL\\repos\\0000-data\\v1.1.2\\templates\\complete\\config.yaml"
│
│ Invalid value for "path" parameter: no file exists at "C:\\data-uni\\OneDrive\\02.00.00.GENERAL\\repos\\0000-data\\v1.1.2\\templates\\complete\\config.yaml"; this function works only     
│ with files that are distributed as part of the configuration source code, so if this file will be created by a resource in this configuration you must instead obtain this result from an  
│ attribute of that resource.
╵
pwsh-7.4.1>
```

### Expected Behaviour (Required)

That the value for "path" parameter would be valid.

### Actual Behaviour (Required)

╷
│ Error: Invalid function argument
│
│   on locals_files.tf line 4, in locals:
│    4:       content = replace((file(value.path)), "# backend \"azurerm\" {}", var.create_bootstrap_resources_in_azure ? "backend \"azurerm\" {}" : "backend \"local\" {}")
│     ├────────────────
│     │ value.path is "...<redacted>\\v1.1.2\\templates\\complete\\config.yaml"
│
│ Invalid value for "path" parameter: no file exists at "...<redacted>\v1.1.2\\templates\\complete\\config.yaml"; this function works only     
│ with files that are distributed as part of the configuration source code, so if this file will be created by a resource in this configuration you must instead obtain this result from an  
│ attribute of that resource.

### Steps to Reproduce (Optional)

New-ALZEnvironment -alzIacProvider "terraform" -alzCicdPlatform "local" -inputs .\inputs.yml -Verbose

### Important Factoids (Optional)

Using default location as uksouth.

### References (Optional)

1. https://stackoverflow.com/questions/67776525/locals-depends-on-terraform
2. https://developer.hashicorp.com/terraform/language/modules/syntax#accessing-module-output-values
