### ISSUE TITLE
bug:  configuration_file_path does not work with dot-slash notation

### ISSUE THREAD

**Issue by terrymandin** [Azure/alz-terraform-accelerator#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bootstrap or Starter Module Deployment? (Required)

starter_module

### ALZ-PowerShell-Module Version (Required)

1.1.6

### alz-terraform-accelerator Version (Required)

1.1.2

### Starter Module (Required)

complete

### Input arguments of the ALZ-PowerShell-Module (Required)

```YAML
New-ALZEnvironment -i "terraform" -c "local"  -Inputs "./inputs.yaml"
```

### Contents of the configuration file used for the `complete` starter module. (Optional)

```YAML
---
# GitHub Bootstrap Variables
# To run:
#   1. Replace all variables "<>" with your values
#   2. Review all defaulted variables to ensure they are correct
#   3. Run the following command:
#
#   New-ALZEnvironment -i "terraform" -c "github" -inputs "C:\\<directories>\\inputs.yaml"

# The starter module to use for the deployment. (e.g. 'complete')
starter_module: "complete"

# Personal access token for GitHub
github_personal_access_token: "token"

# The name of your GitHub organization. This is the section of the url after 'github.com'. E.g. enter 'my-org' for 'https://github.com/my-org'
github_organization_name: "my-org"

# Azure Deployment location for the bootstrap resources (e.g. storage account, identities, etc)
# (An Azure deployment location e.g. 'uksouth')
bootstrap_location: "eastus"

# Controls whether to use a separate repository to store action templates. This is an extra layer of security to ensure that the azure credentials
# can only be leveraged for the specified workload
use_separate_repository_for_workflow_templates: "true"

# Azure Subscription ID for the bootstrap resources (e.g. storage account, identities, etc). Leave empty to use the az login subscription
# (A valid subscription id GUID e.g. '12345678-1234-1234-1234-123456789012')
bootstrap_subscription_id: "id"

# Used to build up the default resource names (e.g. rg-<service_name>-mgmt-uksouth-001)
# (A valid Azure name with no hyphens and limited length e.g. 'abcd')
service_name: "alz"

# Used to build up the default resource names (e.g. rg-alz-<environment_name>-uksouth-001)
# (A valid Azure name with no hyphens and limited length e.g. 'abcd')
environment_name: "mgmt"

# Used to build up the default resource names (e.g. rg-alz-mgmt-uksouth-<postfix_number>)
# (A number e.g. '1234')
postfix_number: "1"

# Controls whether to use self-hosted runners for the actions
use_self_hosted_runners: "true"

# Controls whether to use private networking for the runner to storage account communication
use_private_networking: "false"

# Allow access to the storage account from the current IP address. We recommend this is kept off for security
allow_storage_access_from_my_ip: "true"

# Apply stage approvers to the action / pipeline, must be a list of SPNs separate by a comma (e.g. abcdef@microsoft.com,ghijklm@microsoft.com)
apply_approvers: "emailaddress"

# The root parent management group display name. This will default to 'Tenant Root Group' if not supplied
root_parent_management_group_display_name: "IntermediateGroup"

# Starter Module Specific Variables

# The location for Azure resources. (e.g 'uksouth')
# (An Azure deployment location e.g. 'uksouth')
default_location: "eastus"

# The default postfix for Azure resources. (e.g 'landing-zone') #
# (A valid Azure name e.g. 'my-azure-name')
default_postfix: ""

# This is the id of the management group that the ALZ hierarchy will be nested under, will default to the Tenant Root Group
# (A valid Azure name e.g. 'my-azure-name')
root_parent_management_group_id: "int_grp"

# value of the subscription id for the Management subscription
# (A valid subscription id GUID e.g. '12345678-1234-1234-1234-123456789012')
subscription_id_management: "subid"

# value of the subscription id for the Connectivity subscription
# (A valid subscription id GUID e.g. '12345678-1234-1234-1234-123456789012')
subscription_id_connectivity: "subid"

# value of the subscription id for the Identity subscription
# (A valid subscription id GUID e.g. '12345678-1234-1234-1234-123456789012')
subscription_id_identity: "subid"

# The path of the configuration file
# (A valid yaml or json configuration file path e.g. './my-folder/my-config-file.yaml' or `c:\\my-folder\\my-config-file.yaml`)
configuration_file_path: "./hubandspoke.yaml"
```

### Debug Output/Panic Output (Optional)

```shell
Unfortunately, didn't capture this when going through with the customer.
```

### Expected Behaviour (Required)

I should be able to set a configuration_file_path of "./hubandspoke.yaml".  This fails and I have to enter the full path

### Actual Behaviour (Required)

The deployment fails.
