### ISSUE TITLE
bug: Error: Invalid index - var.runner_groups is empty map of string

### ISSUE THREAD

**Issue by GraemeMeyerGT** [Azure/alz-terraform-accelerator#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bootstrap or Starter Module Deployment? (Required)

bootstrap

### ALZ-PowerShell-Module Version (Required)

1.1.6

### alz-terraform-accelerator Version (Required)

1.1.2

### Starter Module (Required)

basic

### Input arguments of the ALZ-PowerShell-Module (Required)

```YAML
`New-ALZEnvironment -alzIacProvider "terraform" -alzCicdPlatform "github"`


PS > cat .\v1.1.2\cache*.json
{
  "allow_storage_access_from_my_ip": "false",
  "apply_approvers": "REDACTED",
  "bootstrap_location": "uksouth",
  "bootstrap_subscription_id": "838e6eae-905a-4a0f-b190-dbf9563d6d7a",
  "environment_name": "mgmt",
  "github_organization_name": "ORG-NAME",
  "github_personal_access_token": "REDACTED",
  "postfix_number": 1,
  "root_parent_management_group_display_name": "Root Management Group",
  "service_name": "alz",
  "starter_module": "basic",
  "use_private_networking": "true",
  "use_self_hosted_runners": "false",
  "use_separate_repository_for_workflow_templates": "true"
}
{
  "default_location": "uksouth",
  "root_id": "es",
  "root_name": "Enterprise-Scale",
  "subscription_id_connectivity": "838e6eae-905a-4a0f-b190-dbf9563d6d7a",
  "subscription_id_identity": "09893b15-2009-476e-9363-33a25bbe0499",
  "subscription_id_management": "4b7aad5d-5944-47cc-abb8-aac7407a1549"
}
```
```


### Contents of the configuration file used for the `complete` starter module. (Optional)

_No response_

### Debug Output/Panic Output (Optional)

```shell
<script src="https://gist.github.com/GraemeMeyerGT/63ba7a1df31683288c6035cf09fc5c96.js"></script>
```

### Expected Behaviour (Required)

I was expecting the Terraform accelerator to deploy the basic configuration of the Azure Landing Zone into my Azure tenant, and use my GitHub Enterprise Organization for the CI/CD pipeline and repo storage, with GitHub's own hosted/native runners.

### Actual Behaviour (Required)

```PowerShell
Plan: 225 to add, 0 to change, 0 to destroy.
╷
│ Error: Invalid index
│
│   on ..\modules\github\locals.tf line 41, in locals:
│   41:   runner_group_name = data.github_organization.alz.plan == local.enterprise_plan ? github_actions_runner_group.alz[keys(var.runner_groups)[0]].name : var.default_runner_group_name
│     ├────────────────
│     │ var.runner_groups is empty map of string
│
│ The given key does not identify an element in this collection value: the collection has no elements.
```

### Steps to Reproduce (Optional)

This happens reliably every time I run the `New-ALZEnvironment -alzIacProvider "terraform" -alzCicdPlatform "github"` command with the given configuration options. I think if I change to using self-hosted runners, the error disappears and I move further into the process (and in my case hit a different error), but I want to use GitHub's native runners so I don't incur any unnecessary cost in Azure, or complicate the design. We already have active pipelines in our GH org using the native runners, so I know they work in general.

I followed the configuration guide for the PAT, and double-checked the allowed capabilities and it all seems to be as-prescribed.

I'm concerned that [the documentation](https://github.com/Azure/alz-terraform-accelerator/wiki/%5BUser-Guide%5D-Quick-Start-Phase-2-GitHub) on configuring the runner type to reference Azure DevOps, not GitHub Enterprise:

> `use_self_hosted_agents`: This controls if you want to deploy self-hosted agents. If you are using `ManagedServiceIdentity` for `azure_devops_authentication_scheme`, then you will need to deploy self-hosted agents as part of the bootstrap, so this setting will have no effect. This will default to true.

There are no issues or any more documentation referencing this issue or configuration that I can find - is using GitHub an uncommon choice? Since only GitHub enterprise is supported, and GitHub's own/native runners are included in GitHub Enterprise, I would have expected that to be the default choice. There doesn't seem to be any documentation explaining how self-hosted runners work, what they do or why they might be the default configuration option. That could be a useful improvement, at least for GitHub users.

### Important Factoids (Optional)

Public/normal Azure, GitHub Enterprise Org, Windows 11 with PowerShell 7.4

### References (Optional)

[[User Guide] Quick Start Phase 2 GitHub - 2.2.2 GitHub](https://github.com/Azure/alz-terraform-accelerator/wiki/%5BUser-Guide%5D-Quick-Start-Phase-2-GitHub)
