### ISSUE TITLE
bug: After Creation a Public IP "Audit-PublicIpAddresses-UnusedResourcesCostOptimization" cannot be updated. Policy definition is missing

### ISSUE THREAD

**Issue by alenat10** [Azure/alz-terraform-accelerator#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bootstrap or Starter Module Deployment? (Required)

starter_module

### ALZ-PowerShell-Module Version (Required)

2.0.3

### alz-terraform-accelerator Version (Required)

2.0.3

### Starter Module (Required)

complete

### Input arguments of the ALZ-PowerShell-Module (Required)

```YAML
bootstrap-cache.json
{
  "allow_storage_access_from_my_ip": "false",
  "apply_approvers": "***",
  "azure_devops_agents_personal_access_token": "***",
  "azure_devops_authentication_scheme": "WorkloadIdentityFederation",
  "azure_devops_create_project": "true",
  "azure_devops_organization_name": "***",
  "azure_devops_personal_access_token": "***",
  "azure_devops_project_name": "***-alz",
  "azure_devops_use_organisation_legacy_url": "false",
  "bootstrap_location": "westus2",
  "bootstrap_subscription_id": "***",
  "environment_name": "mgmt",
  "postfix_number": "1",
  "service_name": "***",
  "use_private_networking": "false",
  "use_self_hosted_agents": "false",
  "use_separate_repository_for_pipeline_templates": "false"
}
starter-cache.json
{
  "configuration_file_path": "C:\\***\\config-hub-spoke.yaml",
  "default_location": "westus2",
  "default_postfix": "",
  "root_parent_management_group_id": "***",
  "subscription_id_connectivity": "***",
  "subscription_id_identity": "***",
  "subscription_id_management": "***"
}
```

### Debug Output/Panic Output (Optional)

```shell
Error: creating/updating Policy Definition "Audit-PublicIpAddresses-UnusedResourcesCostOptimization": policy.DefinitionsClient#CreateOrUpdateAtManagementGroup: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '***' with object id '***' does not have authorization to perform action 'Microsoft.Authorization/policyDefinitions/write' over scope '/providers/Microsoft.Management/managementGroups/***/providers/Microsoft.Authorization/policyDefinitions/Audit-PublicIpAddresses-UnusedResourcesCostOptimization' or the scope is invalid. If access was recently granted, please refresh your credentials."
│ 
│   with module.enterprise_scale[0].azurerm_policy_definition.enterprise_scale["/providers/Microsoft.Management/managementGroups/***/providers/Microsoft.Authorization/policyDefinitions/Audit-PublicIpAddresses-UnusedResourcesCostOptimization"],
│   on .terraform/modules/enterprise_scale/resources.policy_definitions.tf line 1, in resource "azurerm_policy_definition" "enterprise_scale":
│    1: resource "azurerm_policy_definition" "enterprise_scale" {
│
```

### Expected Behaviour (Required)

policy definition is changed

### Actual Behaviour (Required)

policy definition is missing

### Steps to Reproduce (Optional)

Run CD pipeline created by the accelerator
