### ISSUE TITLE
bug: Starter module deployment interrupted by HTTP 409 from Docker registry

### ISSUE THREAD

**Issue by baptista138** [Azure/alz-terraform-accelerator#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bootstrap or Starter Module Deployment? (Required)

starter_module

### ALZ-PowerShell-Module Version (Required)

2.2.0

### alz-terraform-accelerator Version (Required)

2.2.0

### Starter Module (Required)

basic

### Input arguments of the ALZ-PowerShell-Module (Required)

```YAML
{
  "default_location": "northeurope",
  "root_id": "es",
  "root_name": "Enterprise-Scale",
  "root_parent_management_group_id": "<redacted>",
  "subscription_id_connectivity": "<redacted>",
  "subscription_id_identity": "<redacted>",
  "subscription_id_management": "<redacted>"
}
```

### Debug Output/Panic Output (Optional)

```YAML
Error: creating Container Group (Subscription: "<redacted>" 
Resource Group Name: "<redacted>" 
Container Group Name: "<redacted>"): performing ContainerGroupsCreateOrUpdate: unexpected status 409 (409 Conflict) with error: RegistryErrorResponse: An error response is received from the docker registry 'index.docker.io'. Please retry later.

with module.azure.azurerm_container_group.alz["agent_01"],
on ..\..\modules\azure\container_instances.tf line 1, in resource "azurerm container_group" "alz":
1: resource "azurerm_container_group" "alz" {
```

### Expected Behaviour (Required)

Container instances for self-hosted agents should have been deployed successfully by the starter module.

### Actual Behaviour (Required)

Starter module deployment interrupted by HTTP 409 from Docker registry, when trying to deploy container instances for self-hosted agents.
